export type AdminUserRole = 'admin' | 'agent' | 'seller' | 'buyer'
export type AdminUserStatus = 'active' | 'inactive'

export interface AdminUserItem {
  id: number
  fullName: string
  username: string
  email: string
  phone: string
  role: AdminUserRole
  status: AdminUserStatus
  joinedDate: string // YYYY-MM-DD format
  avatarUrl?: string
  location?: string
  lastActive?: string
  department?: string
  listingsCount?: number
}

export const initialAdminUsers: AdminUserItem[] = [
  // 8 Admins
  {
    id: 1,
    fullName: 'Raviraj Chhasatiya',
    username: 'raviraj',
    email: 'raviraj.c@reozom.com',
    phone: '(555) 234-5678',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-01-15',
    location: 'Austin, TX',
    lastActive: 'Just now',
    department: 'Engineering & Platform',
    listingsCount: 42,
  },
  {
    id: 2,
    fullName: 'Sarah Miller',
    username: 'sarah.m',
    email: 'sarah.miller@reozom.com',
    phone: '(555) 345-6789',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-02-10',
    location: 'Ann Arbor, MI',
    lastActive: '12 mins ago',
    department: 'Operations',
    listingsCount: 28,
  },
  {
    id: 3,
    fullName: 'David Chen',
    username: 'davidchen',
    email: 'david.chen@reozom.com',
    phone: '(555) 456-7890',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-03-01',
    location: 'San Francisco, CA',
    lastActive: '1 hour ago',
    department: 'Compliance',
    listingsCount: 19,
  },
  {
    id: 4,
    fullName: 'Elena Rostova',
    username: 'elena.r',
    email: 'elena.r@reozom.com',
    phone: '(555) 567-8901',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-04-12',
    location: 'Chicago, IL',
    lastActive: '3 hours ago',
    department: 'Security & MLS',
    listingsCount: 35,
  },
  {
    id: 5,
    fullName: 'Marcus Vance',
    username: 'marcus.v',
    email: 'marcus.v@reozom.com',
    phone: '(555) 678-9012',
    role: 'admin',
    status: 'inactive',
    joinedDate: '2024-05-20',
    location: 'Seattle, WA',
    lastActive: '3 days ago',
    department: 'Internal Audit',
    listingsCount: 0,
  },
  {
    id: 6,
    fullName: 'Priya Sharma',
    username: 'priyasharma',
    email: 'priya.sharma@reozom.com',
    phone: '(555) 789-0123',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-06-18',
    location: 'New York, NY',
    lastActive: '5 mins ago',
    department: 'Product Strategy',
    listingsCount: 51,
  },
  {
    id: 7,
    fullName: 'Alex Thorne',
    username: 'alex.t',
    email: 'alex.thorne@reozom.com',
    phone: '(555) 890-1234',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-07-22',
    location: 'Denver, CO',
    lastActive: '2 days ago',
    department: 'Platform Admin',
    listingsCount: 14,
  },
  {
    id: 8,
    fullName: 'Nathan Brooks',
    username: 'nbrooks',
    email: 'nathan.b@reozom.com',
    phone: '(555) 901-2345',
    role: 'admin',
    status: 'active',
    joinedDate: '2024-08-30',
    location: 'Boston, MA',
    lastActive: '4 hours ago',
    department: 'Technical Operations',
    listingsCount: 22,
  },

  // 14 Agents
  {
    id: 9,
    fullName: 'James Wilson',
    username: 'jwilson',
    email: 'james.wilson@premierhomes.com',
    phone: '(555) 111-2233',
    role: 'agent',
    status: 'active',
    joinedDate: '2024-09-05',
    location: 'Dallas, TX',
    lastActive: '25 mins ago',
    listingsCount: 18,
  },
  {
    id: 10,
    fullName: 'Amanda Taylor',
    username: 'ataylor',
    email: 'amanda.t@realtypros.com',
    phone: '(555) 222-3344',
    role: 'agent',
    status: 'active',
    joinedDate: '2024-09-14',
    location: 'Scottsdale, AZ',
    lastActive: '1 day ago',
    listingsCount: 24,
  },
  {
    id: 11,
    fullName: 'Carlos Rodriguez',
    username: 'carlos.r',
    email: 'carlos.r@metrobrokers.com',
    phone: '(555) 333-4455',
    role: 'agent',
    status: 'active',
    joinedDate: '2024-10-02',
    location: 'Miami, FL',
    lastActive: '10 mins ago',
    listingsCount: 31,
  },
  {
    id: 12,
    fullName: 'Jennifer Lawrence',
    username: 'jlawrence',
    email: 'jennifer.l@summitrealty.com',
    phone: '(555) 444-5566',
    role: 'agent',
    status: 'inactive',
    joinedDate: '2024-10-15',
    location: 'Louisville, KY',
    lastActive: '1 week ago',
    listingsCount: 6,
  },
  {
    id: 13,
    fullName: 'Kevin Patel',
    username: 'kpatel',
    email: 'kevin.patel@horizonprops.com',
    phone: '(555) 555-6677',
    role: 'agent',
    status: 'active',
    joinedDate: '2024-11-01',
    location: 'Houston, TX',
    lastActive: '30 mins ago',
    listingsCount: 15,
  },
  {
    id: 14,
    fullName: 'Rachel Green',
    username: 'rgreen',
    email: 'rachel.g@cityrealty.com',
    phone: '(555) 666-7788',
    role: 'agent',
    status: 'active',
    joinedDate: '2024-11-20',
    location: 'New York, NY',
    lastActive: '45 mins ago',
    listingsCount: 22,
  },
  {
    id: 15,
    fullName: 'Michael Chang',
    username: 'mchang',
    email: 'michael.c@bayrealty.com',
    phone: '(555) 777-8899',
    role: 'agent',
    status: 'active',
    joinedDate: '2024-12-05',
    location: 'San Jose, CA',
    lastActive: '2 hours ago',
    listingsCount: 19,
  },
  {
    id: 16,
    fullName: 'Jessica Alba',
    username: 'jalba',
    email: 'jessica.a@coastalliving.com',
    phone: '(555) 888-9900',
    role: 'agent',
    status: 'active',
    joinedDate: '2025-01-10',
    location: 'San Diego, CA',
    lastActive: '3 hours ago',
    listingsCount: 27,
  },
  {
    id: 17,
    fullName: "Brian O'Connor",
    username: 'brian.oc',
    email: 'brian.o@fasttrackrealty.com',
    phone: '(555) 999-0011',
    role: 'agent',
    status: 'inactive',
    joinedDate: '2025-01-25',
    location: 'Los Angeles, CA',
    lastActive: '5 days ago',
    listingsCount: 3,
  },
  {
    id: 18,
    fullName: 'Sophia Martinez',
    username: 'smartinez',
    email: 'sophia.m@vanguardhomes.com',
    phone: '(555) 123-9876',
    role: 'agent',
    status: 'active',
    joinedDate: '2025-02-08',
    location: 'Orlando, FL',
    lastActive: '15 mins ago',
    listingsCount: 16,
  },
  {
    id: 19,
    fullName: 'Daniel Kim',
    username: 'dkim',
    email: 'daniel.kim@pacificrealty.com',
    phone: '(555) 234-8765',
    role: 'agent',
    status: 'active',
    joinedDate: '2025-02-22',
    location: 'Portland, OR',
    lastActive: '1 hour ago',
    listingsCount: 12,
  },
  {
    id: 20,
    fullName: 'Olivia Davis',
    username: 'odavis',
    email: 'olivia.d@apexrealestate.com',
    phone: '(555) 345-7654',
    role: 'agent',
    status: 'active',
    joinedDate: '2025-03-05',
    location: 'Atlanta, GA',
    lastActive: '20 mins ago',
    listingsCount: 29,
  },
  {
    id: 21,
    fullName: 'Ethan Wright',
    username: 'ewright',
    email: 'ethan.w@peakrealty.com',
    phone: '(555) 456-6543',
    role: 'agent',
    status: 'active',
    joinedDate: '2025-03-19',
    location: 'Boulder, CO',
    lastActive: '2 days ago',
    listingsCount: 8,
  },
  {
    id: 22,
    fullName: 'Hannah Abbott',
    username: 'habbott',
    email: 'hannah.a@havenhomes.com',
    phone: '(555) 567-5432',
    role: 'agent',
    status: 'active',
    joinedDate: '2025-04-02',
    location: 'Nashville, TN',
    lastActive: '4 hours ago',
    listingsCount: 14,
  },

  // 21 Sellers
  {
    id: 23,
    fullName: 'Robert Johnson',
    username: 'robert.j',
    email: 'robert.j@gmail.com',
    phone: '(555) 678-4321',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-04-15',
    location: 'Charlotte, NC',
    lastActive: 'Today',
    listingsCount: 2,
  },
  {
    id: 24,
    fullName: 'Emily Watson',
    username: 'emily.w',
    email: 'emily.watson@outlook.com',
    phone: '(555) 789-3210',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-04-28',
    location: 'Minneapolis, MN',
    lastActive: 'Yesterday',
    listingsCount: 1,
  },
  {
    id: 25,
    fullName: 'Thomas Anderson',
    username: 'tanderson',
    email: 'neo.anderson@matrixmail.com',
    phone: '(555) 890-2109',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-05-11',
    location: 'Chicago, IL',
    lastActive: '3 hours ago',
    listingsCount: 3,
  },
  {
    id: 26,
    fullName: 'Maria Santos',
    username: 'mariasantos',
    email: 'maria.s@yahoo.com',
    phone: '(555) 901-1098',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-05-25',
    location: 'Tampa, FL',
    lastActive: 'Just now',
    listingsCount: 1,
  },
  {
    id: 27,
    fullName: 'William Clark',
    username: 'wclark',
    email: 'william.clark@icloud.com',
    phone: '(555) 012-0987',
    role: 'seller',
    status: 'inactive',
    joinedDate: '2025-06-08',
    location: 'Detroit, MI',
    lastActive: '2 weeks ago',
    listingsCount: 1,
  },
  {
    id: 28,
    fullName: 'Lisa Cuddy',
    username: 'lcuddy',
    email: 'lisa.cuddy@princetonhealth.org',
    phone: '(555) 123-1122',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-06-20',
    location: 'Princeton, NJ',
    lastActive: '1 hour ago',
    listingsCount: 4,
  },
  {
    id: 29,
    fullName: 'Gregory House',
    username: 'ghouse',
    email: 'greg.house@diagmed.com',
    phone: '(555) 234-2233',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-07-04',
    location: 'Trenton, NJ',
    lastActive: '6 hours ago',
    listingsCount: 2,
  },
  {
    id: 30,
    fullName: 'Allison Cameron',
    username: 'acameron',
    email: 'allison.c@gmail.com',
    phone: '(555) 345-3344',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-07-18',
    location: 'Philadelphia, PA',
    lastActive: '2 days ago',
    listingsCount: 1,
  },
  {
    id: 31,
    fullName: 'Eric Foreman',
    username: 'eforeman',
    email: 'eric.foreman@neurocare.org',
    phone: '(555) 456-4455',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-08-01',
    location: 'Newark, NJ',
    lastActive: 'Yesterday',
    listingsCount: 2,
  },
  {
    id: 32,
    fullName: 'Robert Chase',
    username: 'rchase',
    email: 'robert.chase@sydneyhealth.com',
    phone: '(555) 567-5566',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-08-15',
    location: 'San Diego, CA',
    lastActive: '4 hours ago',
    listingsCount: 3,
  },
  {
    id: 33,
    fullName: 'John Watson',
    username: 'jwatson',
    email: 'john.watson@bakerst.co.uk',
    phone: '(555) 678-6677',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-08-29',
    location: 'London, UK',
    lastActive: '30 mins ago',
    listingsCount: 1,
  },
  {
    id: 34,
    fullName: 'Mary Morstan',
    username: 'mmorstan',
    email: 'mary.watson@mail.com',
    phone: '(555) 789-7788',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-09-12',
    location: 'Surrey, UK',
    lastActive: '5 hours ago',
    listingsCount: 1,
  },
  {
    id: 35,
    fullName: 'Irene Adler',
    username: 'irene.a',
    email: 'the.woman@bohemia.com',
    phone: '(555) 890-8899',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-09-26',
    location: 'Vienna, AT',
    lastActive: '1 day ago',
    listingsCount: 5,
  },
  {
    id: 36,
    fullName: 'Mycroft Holmes',
    username: 'mycroft.h',
    email: 'mycroft.h@diogenes.gov',
    phone: '(555) 901-9900',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-10-10',
    location: 'Pall Mall, UK',
    lastActive: '2 days ago',
    listingsCount: 2,
  },
  {
    id: 37,
    fullName: 'Jim Moriarty',
    username: 'jmoriarty',
    email: 'jim@consultingcrime.org',
    phone: '(555) 012-0011',
    role: 'seller',
    status: 'inactive',
    joinedDate: '2025-10-24',
    location: 'Dublin, IE',
    lastActive: '1 month ago',
    listingsCount: 0,
  },
  {
    id: 38,
    fullName: 'Clara Oswald',
    username: 'coswald',
    email: 'clara.oswald@coalhill.edu',
    phone: '(555) 123-3344',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-11-07',
    location: 'Shoreditch, UK',
    lastActive: 'Today',
    listingsCount: 1,
  },
  {
    id: 39,
    fullName: 'Amy Pond',
    username: 'amypond',
    email: 'amy.williams@leadworth.com',
    phone: '(555) 234-4455',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-11-21',
    location: 'Leadworth, UK',
    lastActive: '4 hours ago',
    listingsCount: 2,
  },
  {
    id: 40,
    fullName: 'Rory Williams',
    username: 'roryw',
    email: 'rory.williams@nurse-care.org',
    phone: '(555) 345-5566',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-12-05',
    location: 'Gloucester, UK',
    lastActive: '6 hours ago',
    listingsCount: 2,
  },
  {
    id: 41,
    fullName: 'River Song',
    username: 'riversong',
    email: 'dr.song@luna-archaeology.edu',
    phone: '(555) 456-6677',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-12-19',
    location: 'Alexandria, VA',
    lastActive: '10 mins ago',
    listingsCount: 4,
  },
  {
    id: 42,
    fullName: 'Donna Noble',
    username: 'donnanoble',
    email: 'donna.noble@chiswick.co.uk',
    phone: '(555) 567-7788',
    role: 'seller',
    status: 'active',
    joinedDate: '2026-01-08',
    location: 'Chiswick, UK',
    lastActive: 'Yesterday',
    listingsCount: 1,
  },
  {
    id: 43,
    fullName: 'Martha Jones',
    username: 'mjones',
    email: 'martha.jones@unit-intl.org',
    phone: '(555) 678-8899',
    role: 'seller',
    status: 'active',
    joinedDate: '2026-01-22',
    location: 'Freemans, UK',
    lastActive: '3 hours ago',
    listingsCount: 1,
  },

  // 14 Buyers
  {
    id: 44,
    fullName: 'Arthur Dent',
    username: 'adent',
    email: 'arthur.dent@galaxymail.com',
    phone: '(555) 789-9900',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-01',
    location: 'Cottington, UK',
    lastActive: '5 mins ago',
  },
  {
    id: 45,
    fullName: 'Ford Prefect',
    username: 'fprefect',
    email: 'ford.prefect@guidepost.org',
    phone: '(555) 890-0011',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-05',
    location: 'Betelgeuse Five',
    lastActive: '12 mins ago',
  },
  {
    id: 46,
    fullName: 'Trillian Astra',
    username: 'trillian',
    email: 'tricia.mcmillan@sub-etha.com',
    phone: '(555) 901-1122',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-10',
    location: 'Islington, UK',
    lastActive: '35 mins ago',
  },
  {
    id: 47,
    fullName: 'Zaphod Beeblebrox',
    username: 'zaphod',
    email: 'president@galaxygov.org',
    phone: '(555) 012-2233',
    role: 'buyer',
    status: 'inactive',
    joinedDate: '2026-02-15',
    location: 'Heart of Gold',
    lastActive: '1 week ago',
  },
  {
    id: 48,
    fullName: 'Dirk Gently',
    username: 'dgently',
    email: 'dirk@holistic-detective.com',
    phone: '(555) 123-4455',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-20',
    location: 'Camden, UK',
    lastActive: '1 hour ago',
  },
  {
    id: 49,
    fullName: 'Richard MacDuff',
    username: 'rmacduff',
    email: 'richard.m@wayforward.com',
    phone: '(555) 234-5566',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-25',
    location: 'Cambridge, UK',
    lastActive: 'Today',
  },
  {
    id: 50,
    fullName: 'Susan Way',
    username: 'susanway',
    email: 'susan.way@gordonway.org',
    phone: '(555) 345-6677',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-01',
    location: 'London, UK',
    lastActive: '2 days ago',
  },
  {
    id: 51,
    fullName: 'Reg Pooh',
    username: 'regpooh',
    email: 'reg.chronotis@stcadds.cam.ac.uk',
    phone: '(555) 456-7788',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-05',
    location: 'Cambridge, UK',
    lastActive: 'Yesterday',
  },
  {
    id: 52,
    fullName: 'Luke Smith',
    username: 'lukesmith',
    email: 'luke.smith@bannermans.edu',
    phone: '(555) 567-8899',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-10',
    location: 'Ealing, UK',
    lastActive: '3 hours ago',
  },
  {
    id: 53,
    fullName: 'Clyde Langer',
    username: 'clanger',
    email: 'clyde.langer@artschool.org',
    phone: '(555) 678-9900',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-15',
    location: 'London, UK',
    lastActive: '4 hours ago',
  },
  {
    id: 54,
    fullName: 'Rani Chandra',
    username: 'rchandra',
    email: 'rani.chandra@investigative.press',
    phone: '(555) 789-0011',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-20',
    location: 'Fleet St, UK',
    lastActive: '30 mins ago',
  },
  {
    id: 55,
    fullName: 'Mickey Smith',
    username: 'msmith',
    email: 'mickey.smith@defender.net',
    phone: '(555) 890-1122',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-25',
    location: 'London, UK',
    lastActive: '1 day ago',
  },
  {
    id: 56,
    fullName: 'Jack Harkness',
    username: 'jharkness',
    email: 'capt.jack@torchwood.gov.uk',
    phone: '(555) 901-2233',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-30',
    location: 'Cardiff, UK',
    lastActive: 'Just now',
  },
  {
    id: 57,
    fullName: 'Gwen Cooper',
    username: 'gcooper',
    email: 'gwen.cooper@torchwood.gov.uk',
    phone: '(555) 012-3344',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-04-05',
    location: 'Cardiff, UK',
    lastActive: '2 hours ago',
  },
]
